version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lastbite_db
    restart: always
    environment:
      POSTGRES_DB: lastbite_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: lastbite_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/venv
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-secret-key-change-in-prod
      - DB_NAME=lastbite_db
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lastbite_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data:
