# Generated by Django 5.2.6 on 2026-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'allergy_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('quantity_remaining', models.PositiveIntegerField(default=1)),
                ('calories', models.PositiveIntegerField(blank=True, help_text='kcal', null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allergy_notes', models.TextField(blank=True, help_text='Free-text allergy notes')),
                ('pickup_start', models.DateTimeField()),
                ('pickup_end', models.DateTimeField()),
                ('expiry_time', models.DateTimeField(help_text='Food must be picked up before this time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('sold_out', 'Sold Out'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergy_tags', models.ManyToManyField(blank=True, related_name='meals', to='meals.allergytag')),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-created_at'],
            },
        ),
    ]
